create table block(
    id SERIAL PRIMARY KEY NOT NULL,
    number INT,
    hash  VARCHAR,
    parent_hash  VARCHAR,
    nonce  VARCHAR,
    sha3_uncles  VARCHAR,
    logs_bloom  VARCHAR,
    transactions_root  VARCHAR,
    state_root  VARCHAR,
    receipts_root  VARCHAR,
    miner  VARCHAR,
    difficulty  VARCHAR,
    total_difficulty  VARCHAR,
    size INT,
    extra_data  VARCHAR,
    gas_limit INT,
    gas_used  INT,
    timestamp  INT,
    uncles  VARCHAR,
    txs  VARCHAR,
    witness  VARCHAR,
    unique(number)
  );